import { Contact } from "@/types";

export const mockContacts: Contact[] = [
  {
    id: "c1",
    name: "Rajesh Kumar",
    phone: "+91 98765 43210",
    email: "rajesh.kumar@gmail.com",
    group: "Premium Customers",
    tags: ["vip", "retail"],
    addedDate: "2024-01-15",
    status: "active",
  },
  {
    id: "c2",
    name: "Priya Sharma",
    phone: "+91 87654 32109",
    email: "priya.sharma@yahoo.com",
    group: "Newsletter",
    tags: ["newsletter", "offers"],
    addedDate: "2024-01-20",
    status: "active",
  },
  {
    id: "c3",
    name: "Amit Patel",
    phone: "+91 76543 21098",
    email: "amit.patel@hotmail.com",
    group: "Premium Customers",
    tags: ["vip", "b2b"],
    addedDate: "2024-02-05",
    status: "active",
  },
  {
    id: "c4",
    name: "Sunita Reddy",
    phone: "+91 65432 10987",
    email: "sunita.reddy@gmail.com",
    group: "Festival Offers",
    tags: ["seasonal", "offers"],
    addedDate: "2024-02-10",
    status: "active",
  },
  {
    id: "c5",
    name: "Mohammad Khan",
    phone: "+91 54321 09876",
    email: "m.khan@outlook.com",
    group: "Newsletter",
    tags: ["newsletter"],
    addedDate: "2024-02-15",
    status: "inactive",
  },
  {
    id: "c6",
    name: "Kavitha Nair",
    phone: "+91 43210 98765",
    email: "kavitha.nair@gmail.com",
    group: "Premium Customers",
    tags: ["vip", "loyalty"],
    addedDate: "2024-03-01",
    status: "active",
  },
  {
    id: "c7",
    name: "Suresh Menon",
    phone: "+91 32109 87654",
    email: "suresh.menon@gmail.com",
    group: "Festival Offers",
    tags: ["seasonal", "retail"],
    addedDate: "2024-03-05",
    status: "active",
  },
  {
    id: "c8",
    name: "Deepika Joshi",
    phone: "+91 21098 76543",
    email: "deepika.joshi@yahoo.com",
    group: "Newsletter",
    tags: ["newsletter", "new"],
    addedDate: "2024-03-10",
    status: "active",
  },
  {
    id: "c9",
    name: "Arjun Singh",
    phone: "+91 10987 65432",
    email: "arjun.singh@gmail.com",
    group: "B2B Partners",
    tags: ["b2b", "partner"],
    addedDate: "2024-03-15",
    status: "active",
  },
  {
    id: "c10",
    name: "Meera Iyer",
    phone: "+91 09876 54321",
    email: "meera.iyer@hotmail.com",
    group: "Premium Customers",
    tags: ["vip", "loyalty", "offers"],
    addedDate: "2024-03-20",
    status: "active",
  },
];

export const contactGroups = [
  "Premium Customers",
  "Newsletter",
  "Festival Offers",
  "B2B Partners",
  "New Leads",
];

export const contactTags = [
  "vip",
  "retail",
  "newsletter",
  "offers",
  "b2b",
  "partner",
  "seasonal",
  "loyalty",
  "new",
];
