import { Template } from "@/types";

export const mockTemplates: Template[] = [
  {
    id: "t1",
    name: "appointment_reminder",
    displayName: "Appointment Reminder",
    category: "UTILITY",
    language: "en_IN",
    status: "APPROVED",
    body: "Hello {{1}}, this is a reminder for your appointment on {{2}} at {{3}}. Please confirm by replying YES. Thank you!",
    variables: ["customer_name", "appointment_date", "appointment_time"],
    createdAt: "2024-01-10",
  },
  {
    id: "t2",
    name: "promo_offer",
    displayName: "Promo Offer",
    category: "MARKETING",
    language: "en_IN",
    status: "APPROVED",
    body: "🎉 Hi {{1}}! Exciting news! Get {{2}}% OFF on all products this weekend. Use code {{3}} at checkout. Valid till Sunday midnight. Shop now!",
    variables: ["customer_name", "discount_percentage", "promo_code"],
    createdAt: "2024-01-15",
  },
  {
    id: "t3",
    name: "welcome_message",
    displayName: "Welcome Message",
    category: "UTILITY",
    language: "en_IN",
    status: "APPROVED",
    body: "Welcome to {{1}}, {{2}}! 🙏 We're thrilled to have you on board. Your account is now active. Reply HELP for assistance anytime.",
    variables: ["company_name", "customer_name"],
    createdAt: "2024-01-20",
  },
  {
    id: "t4",
    name: "payment_reminder",
    displayName: "Payment Reminder",
    category: "UTILITY",
    language: "en_IN",
    status: "PENDING",
    body: "Dear {{1}}, your payment of ₹{{2}} is due on {{3}}. Please make the payment to avoid any service interruption. Pay now: {{4}}",
    variables: ["customer_name", "amount", "due_date", "payment_link"],
    createdAt: "2024-02-01",
  },
  {
    id: "t5",
    name: "festival_offer",
    displayName: "Festival Offer",
    category: "MARKETING",
    language: "en_IN",
    status: "APPROVED",
    body: "🪔 Happy {{1}}, {{2}}! Celebrate with exclusive festival deals - up to {{3}}% off! Limited time offer. Don't miss out! 🎆",
    variables: ["festival_name", "customer_name", "discount"],
    createdAt: "2024-02-10",
  },
];
